Fix typescript error
noCircularImportsRule.ts:118:34 - error TS2339: Property 'fileName' does not exist on type 'ModuleBlock | SourceFile'.
  Property 'fileName' does not exist on type 'ModuleBlock'.

118     const fileName = node.parent.fileName
                                     ~~~~~~~~